version: "3.5"

services:
  mongo:
    image: mongo:latest
    container_name: mongotest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: testdb
    ports:
      - 27017:27017
    networks:
      - backend

  application:
    image: mongo-example-application
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    networks:
      - backend

networks:
  backend:
    driver: bridge
